version: '3'
services:    
    nginx:
        image: "jwilder/nginx-proxy"
        container_name: "mist-nginx"
        ports:
            - "443:443"
        volumes:
            - <your_folder>/docker/nginx:/etc/nginx/certs:ro         
            - /var/run/docker.sock:/tmp/docker.sock:ro 
            - /etc/nginx/vhost.d
        restart: always

    automation: 
        image: "tmunzer/mist_automation"
        container_name: "mist-automation"
        depends_on: 
            - nginx
        environment:
            - VIRTUAL_HOST=<your_app_hostname>
        volumes:
            - <your_folder>/docker/mist_automation/automation.yml:/app/automation.yml:ro       
